# Generated by Django 5.0.4 on 2024-05-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs_app', '0002_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.DurationField(),
        ),
    ]
